import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./Header"
import Sidebar from "./components/Sidebar/Sidebar"
import { useTheme } from "react-daisyui";
import { GiSittingDog } from "react-icons/gi";
import Head from "next/head";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dogify",
  description: "Generated by create next app",
  
  // image: <GiSittingDog />
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
<body className="flex w-full h-full relative">  
<Sidebar/>
<div className="w-[] md:ml-[340px] bodycontainer" 
// style={{"width: calc(100% - 2rem)"}}
// style={{width: "calc(100% - 340px)"}}
> 
<Header />
<div className="">
       {children}
       </div>
       </div>      
       </body>
     
    </html>
  );
}
